version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres-filme:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=filme
      - POSTGRES_USER=filme
      - POSTGRES_DB=filme